import { html, type SafeHtml } from '../../util/html.js';

export function apiDocsPage(base: string): SafeHtml {
  return html`<article class="prose">
  <h1>HTTP API</h1>
  <p>Base URL: <code>${base}</code>. The machine-readable description is at <a href="/api/openapi.json"><code>/api/openapi.json</code></a> (OpenAPI 3.1).</p>
  <h2>Authentication</h2>
  <p>Create a personal API key on your <a href="/account">account page</a> and send it as <code>Authorization: Bearer cj_…</code>. Keys carry scopes (<code>schemes:read</code>, <code>schemes:generate</code>, <code>schemes:write</code>) and only ever see the owner’s schemes.</p>
  <h2>Endpoints</h2>
  <table class="table"><thead><tr><th>Method</th><th>Path</th><th>Scope</th><th>Purpose</th></tr></thead><tbody>
  <tr><td>POST</td><td><code>/api/schemes/generate</code></td><td>schemes:generate</td><td>Generate a paired light/dark scheme from <code>{"concept": "…"}</code>. Optional <code>variation</code> and <code>locks</code>. Uses the semantic cache before Jev; <code>"refresh": true</code> asks Jev again and replaces the cached judgement (10 per user per hour).</td></tr>
  <tr><td>GET</td><td><code>/api/schemes</code></td><td>schemes:read</td><td>List your saved schemes (<code>limit</code>, <code>offset</code>).</td></tr>
  <tr><td>POST</td><td><code>/api/schemes</code></td><td>schemes:write</td><td>Save a generated scheme: <code>{"name": "Dynumo", "generationId": "…"}</code>.</td></tr>
  <tr><td>GET</td><td><code>/api/schemes/{idOrSlug}</code></td><td>schemes:read</td><td>Retrieve a saved scheme.</td></tr>
  <tr><td>PATCH</td><td><code>/api/schemes/{idOrSlug}</code></td><td>schemes:write</td><td>Rename or change notes.</td></tr>
  <tr><td>POST</td><td><code>/api/schemes/{idOrSlug}/duplicate</code></td><td>schemes:write</td><td>Duplicate.</td></tr>
  <tr><td>DELETE</td><td><code>/api/schemes/{idOrSlug}</code></td><td>schemes:write</td><td>Delete.</td></tr>
  <tr><td>GET</td><td><code>/api/schemes/{idOrSlug}/export?format=css|json|tailwind|tailwind-v3</code></td><td>schemes:read</td><td>Export.</td></tr>
  </tbody></table>
  <h2>Example</h2>
  <pre class="export-pre">curl -X POST ${base}/schemes/generate \\
  -H "Authorization: Bearer $CHROMAJEV_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"concept": "autumn forest"}'</pre>
  </article>`;
}

export function mcpDocsPage(url: string): SafeHtml {
  return html`<article class="prose">
  <h1>Use ChromaJev from AI assistants (MCP)</h1>
  <p>ChromaJev is a remote MCP server. Add this URL as a custom connector / remote MCP server in your client:</p>
  <pre class="export-pre">${url}</pre>
  <p>Your client will open ChromaJev in a browser so you can sign in with your normal account and approve access. It receives an OAuth access token — never your password.</p>
  <h2>Tools</h2>
  <ul>
    <li><code>generate_colour_scheme</code> — concept → paired light/dark palette with accessibility data (cached judgements cost nothing).</li>
    <li><code>list_colour_schemes</code>, <code>get_colour_scheme</code> — your saved schemes.</li>
    <li><code>save_colour_scheme</code> — save a scheme you just generated by its <code>generation_id</code>.</li>
    <li><code>rename_colour_scheme</code>, <code>delete_colour_scheme</code> — manage saved schemes (write scope; delete is destructive).</li>
  </ul>
  <p>Saved schemes are also readable as resources at <code>chromajev://schemes/{slug}</code>.</p>
  </article>`;
}
