import { MODE_TOKENS, type ModeToken, type ModeTokens } from './types.js';

/** camelCase token → CSS custom property name (primaryForeground → --primary-foreground). */
export function cssVarName(token: ModeToken): string {
  return `--${token.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)}`;
}

export interface ExportableScheme {
  name: string;
  slug?: string;
  concept: string;
  light: ModeTokens;
  dark: ModeTokens;
  algorithmVersion?: string;
}

function block(selector: string, tokens: ModeTokens, colorScheme: 'light' | 'dark'): string {
  const lines = MODE_TOKENS.map((t) => `  ${cssVarName(t)}: ${tokens[t]};`);
  return `${selector} {\n  color-scheme: ${colorScheme};\n${lines.join('\n')}\n}`;
}

/**
 * Light values on :root, dark values under [data-theme="dark"], plus an
 * opt-in prefers-color-scheme block for sites that follow the OS setting.
 */
export function toCss(s: ExportableScheme): string {
  const header = `/* ${s.name} — generated by ChromaJev from "${s.concept.replace(/\*\//g, '* /')}" */`;
  const darkVars = MODE_TOKENS.map((t) => `    ${cssVarName(t)}: ${s.dark[t]};`).join('\n');
  return [
    header,
    block(':root,\n[data-theme="light"]', s.light, 'light'),
    block('[data-theme="dark"]', s.dark, 'dark'),
    `/* Follow the operating system unless a theme is set explicitly. */\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n    color-scheme: dark;\n${darkVars}\n  }\n}`,
  ].join('\n\n') + '\n';
}

export function toJson(s: ExportableScheme): string {
  return (
    JSON.stringify(
      {
        name: s.name,
        ...(s.slug ? { slug: s.slug } : {}),
        concept: s.concept,
        generator: 'ChromaJev',
        ...(s.algorithmVersion ? { algorithmVersion: s.algorithmVersion } : {}),
        light: s.light,
        dark: s.dark,
      },
      null,
      2,
    ) + '\n'
  );
}

/**
 * Tailwind CSS v4 (CSS-first config): the CSS variables above, a `dark`
 * variant bound to [data-theme="dark"], and @theme colours that reference the
 * variables so utilities like `bg-primary` and `text-text-muted` switch mode.
 */
export function toTailwind(s: ExportableScheme): string {
  const theme = MODE_TOKENS.map((t) => `  --color-${cssVarName(t).slice(2)}: var(${cssVarName(t)});`).join('\n');
  return [
    `/* ${s.name} — Tailwind CSS v4 theme generated by ChromaJev */`,
    `@import "tailwindcss";`,
    `@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *));`,
    toCss(s).split('\n').slice(1).join('\n').trim(),
    `@theme inline {\n${theme}\n}`,
  ].join('\n\n') + '\n';
}

/** Tailwind v3 `theme.extend.colors` equivalent, for older projects. */
export function toTailwindV3(s: ExportableScheme): string {
  const colors = MODE_TOKENS.map((t) => `        '${cssVarName(t).slice(2)}': 'var(${cssVarName(t)})',`).join('\n');
  return `// ${s.name} — Tailwind v3 config generated by ChromaJev. Pair with the CSS variables export.\n/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  darkMode: ['selector', '[data-theme="dark"]'],\n  theme: {\n    extend: {\n      colors: {\n${colors}\n      },\n    },\n  },\n};\n`;
}

export type ExportFormat = 'css' | 'json' | 'tailwind' | 'tailwind-v3';
export const EXPORT_FORMATS: ExportFormat[] = ['css', 'json', 'tailwind', 'tailwind-v3'];

export function exportScheme(s: ExportableScheme, format: ExportFormat): { body: string; contentType: string; extension: string } {
  switch (format) {
    case 'css':
      return { body: toCss(s), contentType: 'text/css; charset=utf-8', extension: 'css' };
    case 'json':
      return { body: toJson(s), contentType: 'application/json; charset=utf-8', extension: 'json' };
    case 'tailwind':
      return { body: toTailwind(s), contentType: 'text/css; charset=utf-8', extension: 'tailwind.css' };
    case 'tailwind-v3':
      return { body: toTailwindV3(s), contentType: 'text/javascript; charset=utf-8', extension: 'tailwind.config.js' };
  }
}
